## family models
library(mctoolsr)
library(tidyverse)
library(glmulti)
# input data
tax_table_nem = 'nem_asv_gt.txt'
map_fp = 'metadata_fall_gt.txt'

input_nem = load_taxa_table(tax_table_nem, map_fp)
input_nem_ra = convert_to_relative_abundances(input_nem)
input_nem_ra$map_loaded$sampleID <- row.names(input_nem_ra$map_loaded)
input_nem_ra = filter_data(input_nem_ra, filter_cat = 'sampleID',
                           filter_vals = c("F.10.O_F"))


# Summarize at the family level #
sumtax_family <- summarize_taxonomy(input_nem_ra, level = 4, report_higher_tax = F)

# clean up names... create separate family level taxonomy
family_taxonomy <- as.data.frame(rownames(sumtax_family))
family_taxonomy$label <- family_taxonomy$`rownames(sumtax_family)`

# go by labels, flip
rownames(sumtax_family) <- family_taxonomy$label
sumtax_family.t <- as.data.frame(t(sumtax_family))

#map
map_model <- input_nem_ra$map_loaded

# merge family table and map
family_wmap <- merge(sumtax_family.t, map_model, by = 0)

Cyatholaimidae<-lmer(Cyatholaimidae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Mermithidae<-lmer(Mermithidae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Trichostrongylidae<-lmer(Trichostrongylidae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Alaimidae<-lmer(Alaimidae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Bastianiidae<-lmer(Bastianiidae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Bunonematidae<-lmer(Bunonematidae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Cephalobidae<-lmer(Cephalobidae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Chronogastridae<-lmer(Chronogastridae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Comesomatidae<-lmer(Comesomatidae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Cryptonchidae<-lmer(Cryptonchidae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Diplogasteridae<-lmer(Diplogasteridae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Diplopeltidae<-lmer(Diplopeltidae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Drilonematidae<-lmer(Drilonematidae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Haliplectidae<-lmer(Haliplectidae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Isolaimiidae<-lmer(Isolaimiidae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Microlaimidae<-lmer(Microlaimidae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Monhysteridae<-lmer(Monhysteridae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Neodiplogasteridae<-lmer(Neodiplogasteridae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Odontolaimidae<-lmer(Odontolaimidae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Plectidae<-lmer(Plectidae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Prismatolaimidae<-lmer(Prismatolaimidae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Rhabditidae<-lmer(Rhabditidae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Rhabdolaimidae<-lmer(Rhabdolaimidae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Allantonematidae<-lmer(Allantonematidae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Steinernematidae<-lmer(Steinernematidae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Aphelenchidae<-lmer(Aphelenchidae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Aphelenchoididae<-lmer(Aphelenchoididae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Diphtherophoridae<-lmer(Diphtherophoridae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Leptonchidae<-lmer(Leptonchidae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Tylencholaimellidae<-lmer(Tylencholaimellidae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Tylencholaimidae<-lmer(Tylencholaimidae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Aporcelaimidae<-lmer(Aporcelaimidae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Chrysonematidae<-lmer(Chrysonematidae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Dorylaimidae<-lmer(Dorylaimidae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Mydonomidae<-lmer(Mydonomidae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Nordiidae<-lmer(Nordiidae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Qudsianematidae<-lmer(Qudsianematidae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Thornenematidae<-lmer(Thornenematidae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Anguinidae<-lmer(Anguinidae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Belondiridae<-lmer(Belondiridae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Belonolaimidae<-lmer(Belonolaimidae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Criconematidae<-lmer(Criconematidae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Hemicycliophoridae<-lmer(Hemicycliophoridae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Hoplolaimidae<-lmer(Hoplolaimidae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Longidoridae<-lmer(Longidoridae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Meloidogynidae<-lmer(Meloidogynidae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Merliniidae<-lmer(Merliniidae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Pratylenchidae<-lmer(Pratylenchidae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Telotylenchidae<-lmer(Telotylenchidae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Trichodoridae<-lmer(Trichodoridae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Tylenchulidae<-lmer(Tylenchulidae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Actinolaimidae<-lmer(Actinolaimidae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Anatonchidae<-lmer(Anatonchidae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Ironidae<-lmer(Ironidae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Mononchidae<-lmer(Mononchidae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Mylonchulidae<-lmer(Mylonchulidae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Nygolaimidae<-lmer(Nygolaimidae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Tobrilidae<-lmer(Tobrilidae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Trischistomatidae<-lmer(Trischistomatidae~ Habitat*Ecosystem + (1|Site), data = family_wmap)
Tylenchidae<-lmer(Tylenchidae~ Habitat*Ecosystem + (1|Site), data = family_wmap)

anova(Cyatholaimidae)
anova(Mermithidae)
anova(Trichostrongylidae)
anova(Alaimidae)
anova(Bastianiidae)
anova(Bunonematidae)
anova(Cephalobidae)
anova(Chronogastridae)
anova(Comesomatidae)
anova(Cryptonchidae)
anova(Diplogasteridae)
anova(Diplopeltidae)
anova(Drilonematidae)
anova(Haliplectidae)
anova(Isolaimiidae)
anova(Microlaimidae)
anova(Monhysteridae)
anova(Neodiplogasteridae)
anova(Odontolaimidae)
anova(Plectidae)
anova(Prismatolaimidae)
anova(Rhabditidae)
anova(Rhabdolaimidae)
anova(Allantonematidae)
anova(Steinernematidae)
anova(Aphelenchidae)
anova(Aphelenchoididae)
anova(Diphtherophoridae)
anova(Leptonchidae)
anova(Tylencholaimellidae)
anova(Tylencholaimidae)
anova(Aporcelaimidae)
anova(Chrysonematidae)
anova(Dorylaimidae)
anova(Mydonomidae)
anova(Nordiidae)
anova(Qudsianematidae)
anova(Thornenematidae)
anova(Anguinidae)
anova(Belondiridae)
anova(Belonolaimidae)
anova(Criconematidae)
anova(Hemicycliophoridae)
anova(Hoplolaimidae)
anova(Longidoridae)
anova(Meloidogynidae)
anova(Merliniidae)
anova(Pratylenchidae)
anova(Telotylenchidae)
anova(Trichodoridae)
anova(Tylenchulidae)
anova(Actinolaimidae)
anova(Anatonchidae)
anova(Ironidae)
anova(Mononchidae)
anova(Mylonchulidae)
anova(Nygolaimidae)
anova(Tobrilidae)
anova(Trischistomatidae)
anova(Tylenchidae)  

emmeans(Haliplectidae, ~Habitat)
emmeans(Microlaimidae, ~Habitat)
emmeans(Chronogastridae, ~Habitat)
emmeans(Monhysteridae, ~Habitat)
emmeans(Prismatolaimidae, ~Habitat)

emmeans(Odontolaimidae, ~Ecosystem)
emmeans(Plectidae, ~Ecosystem)
emmeans(Rhabditidae, ~Ecosystem)
emmeans(Microlaimidae, ~Ecosystem)
emmeans(Prismatolaimidae, ~Ecosystem)

emmeans(Tylencholaimidae, pairwise ~Habitat*Ecosystem)
emmeans(Leptonchidae, pairwise ~Habitat*Ecosystem)

emmeans(Chrysonematidae, ~Habitat)
emmeans(Nordiidae, ~Habitat)
emmeans(Chrysonematidae, pairwise ~Habitat*Ecosystem)
emmeans(Dorylaimidae, pairwise ~Habitat*Ecosystem)

emmeans(Criconematidae, ~Ecosystem)
emmeans(Belondiridae, ~Ecosystem)
emmeans(Telotylenchidae, ~Ecosystem)
emmeans(Criconematidae, pairwise ~Habitat*Ecosystem)
emmeans(Tylenchulidae, pairwise ~Habitat*Ecosystem)
